version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angular",
    "react",
    "angularjs",
    "meteor"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo",
    "browser",
    "cypress"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "php"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "sql"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"